[default_config]
assembler = "nasm"
instruction_set = "x86"

[default_config.opts]
compiler = "nasm"
compile_on_save = false
compile_flags_txt = [
  "-i/Users/josiah/Projects/os/boot/src/",
  "-o /dev/null"
]

[[project]]
path = "kernel/arch/i386/"
assembler = "gas"
instruction_set = "x86"

[project.opts]
compiler = "gcc"
compile_flags_txt = [
  "-m32",
  "-x",
  "assembler",
  "-c"
]
